"""Glossaire conformité. Format : (terme, catégorie, définition, décorticage, actualité/échéance).
Pour atteindre 500 concepts : ajoutez des lignes dans concepts_extra.csv
(colonnes : terme,categorie,definition,decorticage,actualite) — chargées automatiquement."""
import os
import pandas as pd

BASE = [
 ("AMLA", "LCB-FT / UE", "Autorité européenne de lutte contre le blanchiment (Francfort), créée par le règlement (UE) 2024/1620.",
  "Supervision directe d'environ 40 entités transfrontalières à haut risque ; coordination des CRF et superviseurs nationaux ; élaboration de normes techniques (RTS) ; pouvoir de sanction.",
  "Montée en puissance 2025-2027, supervision directe attendue à partir de 2028."),
 ("AMLR", "LCB-FT / UE", "Règlement (UE) 2024/1624 : règles LCB-FT directement applicables, sans transposition nationale.",
  "Harmonise vigilance client, bénéficiaires effectifs, PPE, limite de 10 000 € pour les paiements en espèces, périmètre élargi (CASP, crowdfunding, etc.).",
  "Application prévue à partir du 10 juillet 2027 (à vérifier)."),
 ("6e directive LCB-FT (AMLD6)", "LCB-FT / UE", "Directive (UE) 2024/1640 organisant les mécanismes nationaux, registres et supervision.",
  "Pouvoirs des CRF, accès aux registres de bénéficiaires effectifs, comptes bancaires centralisés, coopération entre autorités.",
  "Transposition attendue pour juillet 2027 (à vérifier)."),
 ("KYC", "Vigilance client", "Know Your Customer : identification et vérification de l'identité du client.",
  "Identification, vérification, compréhension de la relation d'affaires, profil de risque, mise à jour périodique.", "Digitalisation (eKYC, identité numérique européenne)."),
 ("CDD / EDD", "Vigilance client", "Customer Due Diligence (standard) / Enhanced Due Diligence (renforcée).",
  "L'EDD s'applique aux PPE, pays à haut risque, relations complexes ; implique source de richesse/fonds, validation hiérarchique, suivi renforcé.", "Critères harmonisés par l'AMLR."),
 ("Bénéficiaire effectif (UBO)", "Vigilance client", "Personne physique qui détient ou contrôle in fine le client.",
  "Seuil usuel de 25 % ; contrôle par d'autres moyens ; registre RBE ; obligation de signaler les divergences.", "Accès au RBE restreint depuis l'arrêt CJUE de novembre 2022."),
 ("PPE (PEP)", "Vigilance client", "Personne politiquement exposée : exerce ou a exercé une fonction publique importante.",
  "Inclut proches et associés ; vigilance renforcée ; réexamen après cessation de fonction (au moins 12 mois).", "Listes de fonctions publiques harmonisées au niveau UE."),
 ("Approche par les risques (RBA)", "Gouvernance", "Principe : adapter les mesures de vigilance au niveau de risque.",
  "Classification des risques (client, produit, géographie, canal), évaluation globale des risques, mesures proportionnées.", "Méthodologies harmonisées par l'AMLA."),
 ("DOS / STR / SAR", "Déclaration", "Déclaration d'opération suspecte à la CRF (TRACFIN en France).",
  "Déclaration sans délai, confidentialité (interdiction de tipping-off), protection du déclarant.", "Format et canaux standardisés au niveau UE."),
 ("TRACFIN", "Autorités FR", "Cellule de renseignement financier française.",
  "Reçoit et analyse les déclarations, transmet à la justice, publie un rapport annuel sur les typologies.", "Coopération renforcée via FIU.net et AMLA."),
 ("ACPR", "Autorités FR", "Autorité de contrôle prudentiel et de résolution : superviseur banque/assurance.",
  "Contrôles sur pièces et sur place, lignes directrices, commission des sanctions.", "Priorités de contrôle LCB-FT et gel des avoirs."),
 ("GAFI / FATF", "Standards", "Organisme intergouvernemental fixant les 40 Recommandations.",
  "Évaluations mutuelles, listes grise (surveillance accrue) et noire (appel à l'action).", "Mise à jour des listes trois fois par an (février, juin, octobre)."),
 ("Liste grise GAFI", "Standards", "Juridictions sous surveillance accrue pour déficiences stratégiques.",
  "Implique vigilance accrue, risques de réputation et de correspondance bancaire.", "Consulter les mises à jour après chaque plénière."),
 ("Sanctions financières ciblées", "Sanctions", "Gel des avoirs et interdiction de mise à disposition de fonds visant personnes/entités listées.",
  "Listes ONU, UE, OFAC, HMT ; filtrage clients et transactions ; gel sans délai ; déclaration à la DG Trésor.", "Rythme élevé de nouveaux paquets russes."),
 ("SDN List (OFAC)", "Sanctions", "Liste des Specially Designated Nationals du Trésor américain.",
  "Règle des 50 % : entités détenues à 50 % ou plus par des SDN sont bloquées ; portée extraterritoriale via le dollar.", "Mises à jour fréquentes, souvent hebdomadaires."),
 ("Règle des 50 %", "Sanctions", "Règle OFAC assimilant aux SDN les entités détenues ≥ 50 % (cumul) par des personnes listées.",
  "L'UE raisonne avec propriété > 50 % ou contrôle ; analyse de la chaîne d'actionnariat indispensable.", "Alignement des pratiques UE/US en discussion."),
 ("Embargo", "Sanctions", "Restriction commerciale ou financière visant un État ou un secteur.",
  "Peut porter sur armes, biens à double usage, énergie, services ; licences et dérogations possibles.", "Embargos sectoriels russes, Iran, Corée du Nord."),
 ("Biens à double usage", "Contrôle export", "Biens civils pouvant avoir un usage militaire.",
  "Règlement (UE) 2021/821 ; licences d'exportation ; vigilance sur utilisateur final et destination.", "Listes élargies aux technologies sensibles."),
 ("Contournement des sanctions", "Sanctions", "Pratiques visant à échapper aux restrictions (pays tiers, sociétés écrans, transbordement).",
  "Signaux d'alerte : routes atypiques, intermédiaires récents, prix anormaux ; clause « no re-export to Russia ».", "Nouvelle infraction pénale UE (directive 2024/1226)."),
 ("Gel des avoirs", "Sanctions", "Mesure bloquant fonds et ressources économiques d'une personne listée.",
  "Registre national des gels (DG Trésor) ; obligation de déclarer ; licences pour dépenses de base.", "Obligation de signalement des actifs gelés."),
 ("Travel Rule (TFR)", "Crypto", "Règlement (UE) 2023/1113 : traçabilité des transferts de fonds et de crypto-actifs.",
  "Transmission des informations sur donneur d'ordre et bénéficiaire pour tous les transferts crypto.", "En vigueur depuis le 30 décembre 2024."),
 ("MiCA", "Crypto", "Règlement sur les marchés de crypto-actifs.",
  "Agrément des CASP, règles pour stablecoins (EMT, ART), obligations de gouvernance et de LCB-FT.", "Pleinement applicable depuis fin 2024."),
 ("DORA", "Résilience", "Règlement sur la résilience opérationnelle numérique du secteur financier.",
  "Gestion du risque TIC, tests de résilience, registre des prestataires tiers, notification d'incidents.", "Applicable depuis le 17 janvier 2025."),
 ("CSRD / CSDDD", "ESG", "Directive de reporting de durabilité / devoir de vigilance des entreprises.",
  "Double matérialité, ESRS, chaînes de valeur, droits humains et environnement.", "Processus « Omnibus » modifiant calendrier et périmètre."),
 ("Greenwashing", "ESG", "Communication environnementale trompeuse.",
  "Risques réglementaires et de réputation ; lignes directrices ESMA/AMF sur les noms de fonds.", "Directive Green Claims en discussion."),
 ("Lanceur d'alerte", "Éthique", "Personne signalant des violations dans l'intérêt général.",
  "Protection contre les représailles, canaux internes et externes, traitement dans des délais encadrés.", "Loi Waserman (2022) et directive UE 2019/1937."),
 ("Sapin II", "Anticorruption", "Loi française de lutte contre la corruption.",
  "8 piliers : cartographie des risques, code de conduite, alerte, évaluation des tiers, contrôles comptables, formation, régime disciplinaire, audit interne.", "Contrôles de l'AFA."),
 ("FCPA", "Anticorruption", "Loi américaine anticorruption à portée extraterritoriale.",
  "Interdit les paiements à des agents publics étrangers ; dispositions comptables pour sociétés cotées.", "Priorités de poursuite redéfinies récemment."),
 ("FATCA / CRS", "Fiscalité", "Échange automatique d'informations fiscales (US / OCDE).",
  "Auto-certification, indices d'américanité, déclaration annuelle.", "DAC8 étend l'échange aux crypto-actifs."),
 ("RGPD & LCB-FT", "Données", "Articulation entre protection des données et obligations de vigilance.",
  "Base légale, minimisation, durées de conservation (5 ans), droit d'accès limité pour les DOS.", "Lignes directrices EDPB/CNIL."),
 ("Filtrage de noms (name screening)", "Outils", "Contrôle des clients et tiers contre listes de sanctions, PPE et médias négatifs.",
  "Algorithmes de correspondance floue, gestion des faux positifs, seuils calibrés, traçabilité.", "Usage croissant de l'IA avec exigences d'explicabilité."),
 ("Adverse media", "Outils", "Recherche d'informations négatives dans la presse et les sources ouvertes.",
  "Pertinence et fiabilité des sources ; documentation de la décision.", "Automatisation via OSINT et LLM."),
 ("Transaction monitoring", "Outils", "Surveillance des opérations pour détecter les comportements atypiques.",
  "Scénarios, seuils, alertes, qualification, DOS ; backtesting et tuning des règles.", "Modèles ML et lignes directrices sur la gouvernance des modèles."),
 ("Correspondent banking", "Risques", "Relations de banque correspondante avec établissements étrangers.",
  "Vigilance renforcée, questionnaire Wolfsberg, restrictions sur banques fictives.", "Dé-risking et accès au dollar."),
 ("Dé-risking", "Risques", "Rupture de relations avec des clients ou segments jugés trop risqués.",
  "Impact sur l'inclusion financière ; le GAFI encourage une approche proportionnée.", "Sujet suivi par l'EBA et le GAFI."),
 ("Placement / Empilement / Intégration", "LCB-FT", "Les trois phases classiques du blanchiment.",
  "Placement : injection des fonds ; empilement : brouillage des traces ; intégration : réinjection dans l'économie légale.", "Typologies : trade-based ML, crypto, immobilier."),
 ("Financement du terrorisme", "LCB-FT", "Collecte ou transfert de fonds destinés à des actes terroristes.",
  "Montants souvent faibles, origine possiblement légale, gel des avoirs, coopération renseignement.", "Surveillance des collectes en ligne et crypto."),
 ("Financement de la prolifération", "Sanctions", "Financement d'armes de destruction massive.",
  "Recommandation 1 du GAFI étendue ; risques liés à l'Iran et à la Corée du Nord ; biens à double usage.", "Évaluation des risques désormais exigée."),
 ("Wolfsberg Group", "Standards", "Association de banques produisant des standards de bonnes pratiques.",
  "Questionnaire CBDDQ, principes sur le filtrage, la surveillance et la corruption.", "Mises à jour régulières des principes."),
 ("Lignes directrices EBA", "Régulation", "Orientations de l'Autorité bancaire européenne sur les risques LCB-FT.",
  "Facteurs de risque, vigilance, gouvernance, restrictions de de-risking.", "Transfert progressif de compétences vers l'AMLA."),
 ("Registre des trusts / RBE", "Transparence", "Registres de transparence sur les structures juridiques.",
  "Accès pour autorités, assujettis et personnes à intérêt légitime ; vérification des divergences.", "Conséquences de la jurisprudence CJUE."),
]

def load_concepts() -> pd.DataFrame:
    df = pd.DataFrame(BASE, columns=["terme", "categorie", "definition", "decorticage", "actualite"])
    extra = os.path.join(os.path.dirname(__file__), "concepts_extra.csv")
    if os.path.exists(extra):
        df = pd.concat([df, pd.read_csv(extra)], ignore_index=True).drop_duplicates("terme")
    return df.sort_values("terme").reset_index(drop=True)
